"use client";
// app/layout.js - Updated with your existing code

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Com/Footer";
import Navbar from "@/Com/Navbar";
import { Provider } from "react-redux";
import store from "./store/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Provider store={store}>
          <Navbar/>
          {children}
          <Footer/>
        </Provider>
      </body>
    </html>
  );
}

// OR for Next.js Pages Router (_app.js)
/*
import { Provider } from 'react-redux';
import store from '../store'; // Adjust path as needed

export default function App({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Component {...pageProps} />
    </Provider>
  );
}
*/